apiVersion: v1
kind: Service
metadata:
  name: tarifas-app-service
  labels:
    app: tarifas-app
spec:
  type: NodePort
  selector:
    app: tarifas-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}          # Service port
      targetPort: {{ .Values.port }}  # Container port
      nodePort: {{ .Values.nodePort }}  # External port (30000-32767)