apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-app
  labels:
    app: reservas-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reservas-app
  template:
    metadata:
      labels:
        app: reservas-app
    spec:
      containers:
      - name: reservas-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.database }}
        - name: REDIS_HOST
          value: {{ .Values.redisHost }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthPath }}
            port: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthPath }}
            port: {{ .Values.port }}
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3
