apiVersion: v1
kind: Service
metadata:
  name: reservas-app-service
  labels:
    app: reservas-app
spec:
  type: NodePort
  selector:
    app: reservas-app
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: {{ .Values.port }}  # Container port
      nodePort: {{ .Values.nodePort }}  # External port (30000-32767)