[pytest]
addopts = --import-mode=importlib
testpaths =
    autenticadorapp/tests
    busquedas_app/tests
    clientesapp/tests
    comentariosapp/tests
    inventario_app/tests
    proveedoresapp/tests
    reserva_app/tests
    tarifasapp/tests
    transaccionesapp/tests