apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-worker-app
  labels:
    app: pagos-worker-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pagos-worker-app
  template:
    metadata:
      labels:
        app: pagos-worker-app
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          command: ["python", "worker_main.py"]

          env:
            - name: SQS_PAGOS_URL
              value: {{ .Values.sqsPagosUrl }}

            - name: SQS_RESERVAS_URL
              value: {{ .Values.sqsReservasUrl }}
            
            - name: DATABASE_URL
              value: {{ .Values.database }}