image:
  repository: 387050840675.dkr.ecr.us-east-1.amazonaws.com/comentarios-app
  tag: v1.0.0

service:
  port: 80

replicaCount: 1

database: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260412200751105600000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db
healthPath: api/v1/reviews/health
port: 3003
nodePort: 30003
