apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  labels:
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-api
        image: 387050840675.dkr.ecr.us-east-1.amazonaws.com/auth-app:v3.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        env:
        - name: DATABASE_URL
          value: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260426211023287000000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db
        readinessProbe:
          httpGet:
            path: api/v1/auth/health
            port: 3004
        livenessProbe:
          httpGet:
            path: api/v1/auth/health
            port: 3004
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3
