apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventarios-app
  labels:
    app: inventarios-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventarios-app
  template:
    metadata:
      labels:
        app: inventarios-app
    spec:
      containers:
      - name: inventarios-api
        image: 387050840675.dkr.ecr.us-east-1.amazonaws.com/inventarios-app:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260411151211056300000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db
        readinessProbe:
          httpGet:
            path: api/v1/inventarios/health
            port: 3000
        livenessProbe:
          httpGet:
            path: api/v1/inventarios/health
            port: 3000
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3
