apiVersion: v1
kind: Service
metadata:
  name: clientes-app-service
  labels:
    app: clientes-app
spec:
  type: NodePort
  selector:
    app: clientes-app
  ports:
    - protocol: TCP
      port: 3007          # Service port
      targetPort: 3007  # Container port
      nodePort: 30007   # External port (30000-32767)