apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-app
  labels:
    app: reservas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-app
  template:
    metadata:
      labels:
        app: reservas-app
    spec:
      containers:
      - name: reservas-api
        image: 387050840675.dkr.ecr.us-east-1.amazonaws.com/reservas-app:v12.0.0
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260323201138153200000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db
        readinessProbe:
          httpGet:
            path: api/v1/reservas/health
            port: 3001
        livenessProbe:
          httpGet:
            path: api/v1/reservas/health
            port: 3001
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3
