apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-worker-app
  labels:
    app: pagos-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos-worker-app
  template:
    metadata:
      labels:
        app: pagos-worker-app
    spec:
      containers:
        - name: worker
          image: 387050840675.dkr.ecr.us-east-1.amazonaws.com/transacciones-app:v8.0.0
          imagePullPolicy: Always

          command: ["python", "worker_main.py"]

          env:
            - name: SQS_PAGOS_URL
              value: https://sqs.us-east-1.amazonaws.com/387050840675/pagos-sqs
            - name: SQS_RESERVAS_URL
              value: https://sqs.us-east-1.amazonaws.com/387050840675/reservas-sqs
            - name: DATABASE_URL
              value: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260426211023287000000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db