apiVersion: apps/v1
kind: Deployment
metadata:
  name: transacciones-app
  labels:
    app: transacciones-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transacciones-app
  template:
    metadata:
      labels:
        app: transacciones-app
    spec:
      containers:
      - name: transacciones-api
        image: 387050840675.dkr.ecr.us-east-1.amazonaws.com/transacciones-app:v5.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: DATABASE_URL
          value: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260426211023287000000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db
        - name: SQS_PAGOS_URL
          value: https://sqs.us-east-1.amazonaws.com/387050840675/pagos-sqs
        - name: SQS_RESERVAS_URL
          value: https://sqs.us-east-1.amazonaws.com/387050840675/reservas-sqs
        readinessProbe:
          httpGet:
            path: api/v1/Transactions/health
            port: 3005
        livenessProbe:
          httpGet:
            path: api/v1/Transactions/health
            port: 3005
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3
