version: 0.2

phases:
  install:
    commands:
      - echo Installing tools...

      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - aws eks update-kubeconfig --region us-east-1 --name proyecto-final-grupo-4
      - echo "=== 1. Verificando identidad IAM ==="
      - aws sts get-caller-identity
      - echo "=== 2. Probando generación manual del token ==="
      - aws eks get-token --cluster-name proyecto-final-grupo-4 --region us-east-1
      - echo "=== 3. Inspeccionando kubeconfig ==="
      - cat ~/.kube/config | grep -A5 "users:"
      - export KUBECONFIG=$HOME/.kube/config
      - IMAGE_URI=$(jq -r '.image_uri' comentariosapp/imageDetail.json)
      - IMAGE_REPO=$(echo $IMAGE_URI | cut -d ':' -f1)
      - IMAGE_TAG=$(echo $IMAGE_URI | cut -d ':' -f2)

  build:
    commands:
      - echo "Deploying with Helm..."
      - helm upgrade --install comentarios-app ./comentariosapp/chart --set image.repository=$IMAGE_REPO --set image.tag=$IMAGE_TAG
      - kubectl apply -f k8s/gateway-ingress.yaml