version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    REPOSITORY_URI: 387050840675.dkr.ecr.us-east-1.amazonaws.com/comentarios-app

phases:
  pre_build:
    commands:
      - echo "Pre-build iniciado en $(date)"

      - cd comentariosapp
      - echo "Instalando dependencias y ejecutando tests..."
      - export PYTHONPATH=.
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pytest tests/ -v

      - echo "Login en ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - echo "Generando tag de imagen..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Build iniciado en $(date)"
      - echo "Construyendo imagen Docker..."
      - docker build -t comentarios-app:$IMAGE_TAG .

      - echo "Taggeando imagen..."
      - docker tag comentarios-app:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build finalizado en $(date)"
      - echo "Pushing imagen a ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo "Generando artifact para deploy..."
      - printf '{"image_uri":"%s"}' "$REPOSITORY_URI:$IMAGE_TAG" > imageDetail.json
      - cat imageDetail.json

artifacts:
  base-directory: .
  files:
    - comentariosapp/imageDetail.json
    - comentariosapp/chart/**/*
    - comentariosapp/buildspec_CD.yml
    - k8s/gateway-ingress.yaml