image:
  repository: 387050840675.dkr.ecr.us-east-1.amazonaws.com/reservas-app
  tag: v1.0.0

service:
  port: 80

replicaCount: 1

database: postgresql://proyectogrupo4:proyectogrupo4@terraform-20260415132532300400000001.cifuwoics1ov.us-east-1.rds.amazonaws.com:5432/proyect_db
redisHost: master.name.igqc6u.use1.cache.amazonaws.com
healthPath: api/v1/reservas/health
port: 3001
nodePort: 30001
