version: '3.9'

services:
  reserva_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reserva_app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/reservas_db
      REDIS_URL: redis://redis:6379/0
      HOLD_TTL_SECONDS: 900

 