apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  labels:
    app: auth-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.database }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthPath }}
            port: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthPath }}
            port: {{ .Values.port }}
          initialDelaySeconds: 5 
          periodSeconds: 30
          failureThreshold: 3
